# Generated by Django 3.0.2 on 2020-01-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='basic_info',
            field=models.CharField(default='Basic Information', max_length=1000),
        ),
    ]
