# Generated by Django 3.0.2 on 2020-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200130_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
