# Generated by Django 3.0.2 on 2020-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200130_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(height_field=300, upload_to='gallery/', width_field=300),
        ),
    ]
