# Generated by Django 3.0.2 on 2020-02-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='items',
        ),
    ]
